# Generated by Django 3.2.6 on 2021-10-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=20)),
                ('imagem', models.CharField(max_length=256)),
                ('preco', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'itens',
            },
        ),
    ]
